---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed.
      become: yes
      apt: update_cache=yes cache_valid_time=3600

  roles:
     - ocha.dotnet-core
     - geerlingguy.git

- hosts: all
  vars:
    - app: /home/{{ ansible_ssh_user }}/di-traning
    - app_name: DiApp
    - publish_path: /var/legolas-di-app
    - service_name: kestrel-legolas-di-app.service

  pre_tasks:
    - name: Update apt cache if needed.
      become: yes
      apt: update_cache=yes cache_valid_time=3600

  tasks:
  - name: "Cloning app repository"
    git:  repo=https://github.com/wlegolas/mao-na-massa-di.git
          dest={{ app }}
          accept_hostkey=yes
          force=yes
          recursive=no

  - name: "Restore nuget packages"
    command: dotnet restore {{ app }}/{{ app_name }}

  - name: "Build project"
    command: dotnet build {{ app }}/{{ app_name }}

  - name: "Publish project"
    command: dotnet publish {{ app }}/{{app_name}} -o {{ publish_path }}

  - name: "Copy service file - Startup script" 
    copy:
      src={{ app }}/server_configs/startup.sh
      dest={{ publish_path }}/startup.sh
      remote_src=yes
      mode=0755

  - name: "Copy service file - Service metadata" 
    copy:
      src={{ app }}/server_configs/{{ service_name }}
      dest=/etc/systemd/system/{{ service_name }}
      remote_src=yes
      #mode=0755
  
  - name: "Set who will execute service"
    lineinfile:
      path=/etc/systemd/system/{{ service_name }}
      state=present
      regexp='.*\%user%$'
      line="User={{ ansible_ssh_user }}"

  - name: "Stop/Disable service: {{ service_name }}" 
    command: systemctl stop {{ service_name }}
  - command: systemctl disable {{ service_name }}

  - name: "Enable service: {{ service_name }}" 
    command: systemctl enable {{ service_name }}

  - name: "Start service: {{ service_name }}"
    command: systemctl start {{ service_name }}