---
- hosts: all
  become: yes

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
     - ocha.dotnet-core
     - geerlingguy.git

- hosts: all
  become: yes
  vars:
    - provision_path: /home/{{ ansible_ssh_user }}/di-provision
    - app_name: DiApp
    - publish_path: /var/legolas-di-app/di-app/publish
    - service_name: kestrel-legolas-di-app.service
    - repo_url: https://github.com/wlegolas/mao-na-massa-di.git

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
  - name: "Generate the SSH key for user {{ ansible_ssh_user }}"
    user:
      name={{ ansible_ssh_user }}
      generate_ssh_key=yes
      ssh_key_bits=2048
      ssh_key_file=.ssh/id_rsa

  - name: "Cloning app repository"
    git: repo={{repo_url}} dest={{ provision_path }}

  - name: "Creates directory to publish the application"
    file:
      path={{ publish_path }}
      state=directory
      owner={{ ansible_ssh_user }}
      group={{ ansible_ssh_user }}
      mode=0775
      recurse=yes

  - name: "Copy service file - Startup script" 
    copy:
      src={{ provision_path }}/server_configs/startup.sh
      dest={{ publish_path }}/startup.sh
      remote_src=yes
      mode=0755

  - name: "Copy service file - Service metadata" 
    copy:
      src={{ provision_path }}/server_configs/{{ service_name }}
      dest=/etc/systemd/system/{{ service_name }}
      remote_src=yes
  
  - name: "Set who will execute service"
    lineinfile:
      path=/etc/systemd/system/{{ service_name }}
      state=present
      regexp='.*\%user%$'
      line="User={{ ansible_ssh_user }}"
  
  - name: "Stop/Disable service: {{ service_name }}" 
    command: systemctl stop {{ service_name }}
  - command: systemctl disable {{ service_name }}
  
  # Reload service, in all cases
  - service:
      name={{ service_name }}
      state=reloaded