---
- hosts: ci
  become: true
  tasks:
    - name: Installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

- hosts: ci
  become: true
  pre_tasks:
    - name: Update apt cache if needed.
      apt: 
        update_cache: yes 
        cache_valid_time: 3600
  roles:
    - role: ocha.dotnet-core
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
    - role: sansible.gocd_server
      gocd_server:
        dependencies:
          skip_java: yes
        aws:
          install_cli: no
    - name: sansible.gocd_agent
      gocd_agent:
        dependencies:
          skip_java: yes
        aws:
          install_cli: no
  tasks:
  - name: "Generate the SSH key for user go"
    user:
      name=go
      generate_ssh_key=yes
      ssh_key_bits=2048
      ssh_key_file=.ssh/id_rsa
